### ISSUE TITLE
RuntimeError: vSphere Network not found [VM-DATA-41]

### ISSUE THREAD

**Issue by devilldog** [CenturyLinkCloud/chef-provisioning-vsphere#13]
Hi we are trying to provision a host but we keep getting the above error, it is indeed the valid vlan/network name, I have tried adding as string and array... no joy

**Comment by DarshanMurthy** [comment]
would mind sharing your configuration file?

**Comment by devilldog** [comment]
https://gist.github.com/devilldog/984d96ace473be6f9ab4

**Comment by DarshanMurthy** [comment]
Ok, try this : network_name: ["'DEV-QA-01'"]...

**Comment by mwrock** [comment]
Could you include the error you are getting either here or in a gist?

**Comment by devilldog** [comment]
DEV-QA-O1 is a data store name.... and the error is 

RuntimeError
    ------------
    vSphere Network not found [VM-DATA-41]

**Comment by mwrock** [comment]
is 'VM-DATA-41' the name of one of your standard switch networks or distributed port groups?

**Comment by devilldog** [comment]
port group

**Comment by mwrock** [comment]
could be that you have nested network folders in which case you would want to include the entire path in the `network_name: 'folder1/VM-DATA-41'`

**Comment by devilldog** [comment]
I will take a look, thanks Matt

**Comment by devilldog** [comment]
That worked, thanks again Matt!

**Comment by DarshanMurthy** [comment]
@devilldog  would mind sharing your config file. I am facing bug (Error forwarding port: could not forward 8889 or 0). Its been a month I'm blocked here. 
Here's is my config file: https://gist.github.com/DarshanMurthy/c4227990c45eacd8c398

Please, let me know if any work-around.
