### ISSUE TITLE
RuntimeError while serializing gateway (xsd:string)

### ISSUE THREAD

**Issue by mschnell42** [CenturyLinkCloud/chef-provisioning-vsphere#14]
Short version:
Has anyone recently be able to use bootstrapping option [:customization_spec][:ipsettings][:gateway]?

Long version:
I'm a Chef, chef-provisioning-vsphere _and_ Ruby newbie.  It is quite likely that I've fat fingered something somewhere. But given I've successfully been able to use the other [:customization_spec][:ipsettings] bootstrapping options, I figured I'd check with the experts. :-)

**************************************************
****** My command line **********************
**************************************************
chef-client -z test1.rb

**************************************************
****** My test1.rb source *********************
**************************************************
require 'chef/provisioning'
require 'chef/provisioning/vsphere_driver'

with_vsphere_driver host: '10.65.42.3',
  insecure: true,
  user:     'some-user1',
  password: 'some-pw1'

with_machine_options :bootstrap_options => {
  datacenter: "SAI Lab",
  network_name: "SAI Network 48 - SDN",
  resource_pool: "10.65.41.2",
  template_name: "GP-small-u14---Mark",
  num_cpus: 2,
  memory_mb: 4096,
  customization_spec: {
    ipsettings: {
      ip: "10.65.48.28",
      subnetMask: "255.255.255.0",
      gateway: "10.65.48.1",
      dnsServerList: ["10.6.16.43", "10.6.17.43"]
    },
  },
  :ssh => {
    :user => 'some-user2',
    :password => 'some-pw2',
    :paranoid => false,
  }
}

machine 'OPnode8-provisioned' do
  recipe 'mysql'
end

**************************************************
****** My error *********************************
**************************************************
<snip snip>
Converging 1 resources
Recipe: @recipe_files::/Users/mschnell/chef-repo/test1.rb
  * machine[OPnode8-provisioned] action converge[2015-07-15T13:37:06-04:00] INFO: Processing machine[OPnode8-provisioned] action converge (@recipe_files::/Users/mschnell/chef-repo/test1.rb line 32)
[2015-07-15T13:37:06-04:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/OPnode8-provisioned

    - creating machine OPnode8-provisioned on vsphere://10.65.42.3/sdk?use_ssl=true&insecure=true
    -   datacenter: "SAI Lab"
    -   network_name: "SAI Network 48 - SDN"
    -   resource_pool: "10.65.41.2"
    -   template_name: "GP-small-u14---Mark"
    -   num_cpus: 2
    -   memory_mb: 4096
    -   customization_spec: {:ipsettings=>{:ip=>"10.65.48.28", :subnetMask=>"255.255.255.0", :gateway=>"10.65.48.1", :dnsServerList=>["10.6.16.43"]}}
    -   ssh: {:user=>"some-user2", :password=>"some-pw2", :paranoid=>false}establishing connection to 10.65.42.3

    - finding networks...
    - network: SAI Network 48 - SDN is a Network
    - changing template nic for SAI Network 48 - SDN
    - customizing OPnode8-provisioned               with static IP 10.65.48.28
RuntimeError while serializing gateway (xsd:string):
"10.65.48.1"
RuntimeError while serializing adapter (CustomizationIPSettings):
CustomizationIPSettings(
  dnsServerList: ["10.6.16.43"],
  gateway: "10.65.48.1",
  ip: CustomizationFixedIp( ipAddress: "10.65.48.28" ),
  subnetMask: "255.255.255.0"
)
RuntimeError while serializing nicSettingMap (CustomizationAdapterMapping):
CustomizationAdapterMapping(
  adapter: CustomizationIPSettings(
    dnsServerList: ["10.6.16.43"],
    gateway: "10.65.48.1",
    ip: CustomizationFixedIp( ipAddress: "10.65.48.28" ),
    subnetMask: "255.255.255.0"
  )
)
<snipsnip>

**************************************************
****** Extra notes ******************************
**************************************************
Given that :gateway is a single address, I copied the syntax that I had successfully used for the :subnetMask & :ip options...
      ip: "10.65.48.28",
      subnetMask: "255.255.255.0",

Just for fun, I tweaked the gateway definition line...
   - from:  gateway: "10.65.48.1",
   - to       gateway: ["10.65.48.1"],
...and I got my VM to instantiate as desired.

So it would seem that the :gateway option seems to use the "list" syntax of the :dnsServerList...
   -       dnsServerList: ["10.6.16.43", "10.6.17.43"]

**************************************************
****** Bottom line ******************************
**************************************************
I have a work around for my :gateway error, but it seems like the :gateway syntax is using a "list" instead of a "single entry".  Is this the intent, or is this an error?

Cheers...  Mark

**Comment by mwrock** [comment]
Thats exactly correct. It expects an array.

Here are the vsphere docs on that: http://pubs.vmware.com/vi30/sdk/ReferenceGuide/vim.vm.customization.IPSettings.html

**Comment by mschnell42** [comment]
Excellent. Thanks for the clarification and, more importantly, the pointer to the VMware docs. :-)

**Comment by DarshanMurthy** [comment]
@mschnell42 would you mind testing my vsphere_config file from your workspace?

**Comment by mschnell42** [comment]
Darshan...  well, it depends upon the level of difficultly and how likely I am to mess up my environment. (Remember, I'm still a newbie at this chef-provisioning stuff. :-)

**Comment by DarshanMurthy** [comment]
can you share your config file? i can try in my set-up..

**Comment by mschnell42** [comment]
I think that we are talking at cross purposes.  Do you want me to run your file(s)?   Or do you want to run my file(s)?

I have a solution (and explanation) for my original problem from mwrock.  My chef-provisioning-sphere set up is currently doing what I want & need.   I'm not sure what would be the benefit of you running my test1.rb file.

**Comment by DarshanMurthy** [comment]
Just in case If I have missed any attributes in config file

**Comment by mschnell42** [comment]
Ah, I see...  well, I'm not using any attributes that you've not already gotten covered.  See below....

********************

   with_vsphere_driver host: '10.65.42.3',
      insecure: true,
      user: 'some-user1',
      password: 'some-pw1'

   with_machine_options :bootstrap_options => {
      datacenter: "SAI Lab",
      network_name: "SAI Network 48 - SDN",
      resource_pool: "10.65.41.2",
      template_name: "GP-small-u14---Mark",
      num_cpus: 2,
      memory_mb: 4096,
      customization_spec: {
         ipsettings: {
            ip: "10.65.48.28",
            subnetMask: "255.255.255.0",
            gateway: "10.65.48.1",
            dnsServerList: ["10.6.16.43", "10.6.17.43"]
            },
         },

      :ssh => {
         :user => 'some-user2',
         :password => 'some-pw2',
         :paranoid => false,
         }
      }

******************
Cheers...

**Comment by mwrock** [comment]
Seems like @DarshanMurthy is having issues with two things:

1. Chef-Zero connectivity
2. SSH xonnectivity to provisioned VM

I don't think these problems are directly related to his configuration options.

Here is what I would suggest for troubleshooting:

Chef-Zero
- Try using the provisioner with a chef server directly:
```
chef-client -c path_to_a_knife.rb -o your_cookbook::your_provisioning_recipe
```
Note: do not use `-z`

- Try using chef-zero to run a non-provisioning recipe. Try a simple recipe that does almost nothing. If that still does not work then your issue is unreleated to chef-provisioning

SSH to provisioned server:
- Try cloning your template using a vmware client instead of chef-provisioning. Can you SSH to the cloned VM using the same credentials you are using with chef-provisioning? If not, then its likely an issue with either the base template or your network.

**Comment by mschnell42** [comment]
Darshan, another suggestion you might try...

When I first starting wanting to do vSphere integrations, I initially works with the vsphere knife plugin (https://github.com/ezrapagel/knife-vsphere). I found it nice in the sense that I could get the vCenter credentials working first, then I moved to actually instantiating VMs from templates.

Once the vCenter credentials are working you can do some quick validation running various knife vsphere sub-commands:
- knife vsphere datastore list
- knife vsphere vlan list
- knife vsphere vm list

The knife-vshpere vCenter credentials go in your knife.rb file.  What I found to be the minimum setting were:
# knife-vphere setting
knife[:vsphere_host] = "10.65.42.3"
knife[:vsphere_user] = "someusername"
knife[:vsphere_pass] = "somepassword"
knife[:vsphere_dc] = "SAI Lab"
# disable SSL sert checking
knife[:vsphere_insecure] = true

Once I was happy with the high level status type access to my vCenter set up, I then started on the VM start up steps. For me that was using the single knife-sphere sub-command inside a bash script:
- knife vsphere vm clone $VMname --start --template $VMtemplate --cspec AutoNode-empty --cips $IPaddr/24 --chostname $Node_name

With the above parameters in my knife.rb file and the "vm clone" sub-command, things worked as I hoped.  Once my knife-sphere environment was working well, it was simple to transition to the the chef-provisioning-vsphere environment.

About the only other comment I'd make is that I tripped over spaces (" ") and capitalization a couple of times in my vSphere Data Center name and my VM Template names.  So be sure you've got those details ironed out.
