### ISSUE TITLE
CHEF server (Help)

### ISSUE THREAD

**Issue by DarshanMurthy** [CenturyLinkCloud/chef-provisioning-vsphere#15]
We are facing some issues with Chef-Zero so is it possible to point toward chef-server instead of local repo.

**Comment by mwrock** [comment]
It definitely is. There are 2 ways to accomplish this:

1. Run the recipe from a chef-server converging node.
2. use `with_chef_server` as described on the [chef-provisioning readme](https://github.com/chef/chef-provisioning#pointing-boxes-at-chef-servers)
