### ISSUE TITLE
What does the error "missing required parameter name" mean

### ISSUE THREAD

**Issue by tyler-ball** [CenturyLinkCloud/chef-provisioning-vsphere#18]
Copying the bug report from https://github.com/chef/chef-provisioning/issues/386

----

Hello,

I am attempting to use the vSphere driver for chef-provisioning.  When I run chef-client, the first VM spins up and converges the recipe without issue.  As soon as it gets to the second VM the chef run dies with the error:

        ====================================================================
    Error executing action `converge` on resource 'machine[chef-2]'
        ====================================================================

    RuntimeError
    ------------
    missing required parameter name

    Resource Declaration:
    ---------------------
    # In /home/chef/.chef/local-mode-cache/cache/cookbooks/my_cookbook/recipes/provision.rb

     46:   machine "chef-#{num}" do
     47:     recipe 'my_cookbook::default'
     48:     attribute %w[foo bar] = baz
     48:   end
     49: end

My provisioning recipe (outside of my vSphere configuration) is simply:

    num_servers = 3

    1.upto(num_servers) do |num|
      machine "chef-#{num}" do
        recipe 'my_cookbook::default'
        attribute %w[foo bar] = baz
      end
    end

This is confusing because the error has the machine name in it, and there is literally no difference between machine one and machine ten.

Changing the above lines to the following allows the VM to spin up without issue:

    #1.upto(num_cassandra_servers) do |num|
      machine "chef-2" do
        recipe 'my_cookbook::default'
        attribute %[foo bar] = baz
      end
    #end

The same cookbook runs fine in test kitchen minus the provisioning bit.

Any help is greatly appreciated.

Thanks!

EDIT:

To add further to my confusion, if I create each machine individually by editing the machine name, e.g. replace "chef-#{num}" with "chef-1", "chef-2", "chef-3", the modify the recipe to use the loop, running chef again on the already running vms completes without issue.

**Comment by tyler-ball** [comment]
Hey @three18ti - would you mind including the full stacktrace from your chef-client run in a gist?  After the failure you should see a message saying something like `full stacktrace exported to ~/.chef/cache/chef-stacktrace.out`.

**Comment by mwrock** [comment]
Thanks for reporting this! I just created a multi machine recipe based on the above code sample and have a repro. I'll post again once I research and fix.

**Comment by mwrock** [comment]
This should be fixed. Please reopen if you continue to see this in 0.7.1 or later.

**Comment by three18ti** [comment]
Thanks Matt! Way too quick for me! was on my to-do list today.  Will test
momentarily.
