### ISSUE TITLE
Attempting to use multiple additional_disk_size_gb 

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#24]
![example1](https://cloud.githubusercontent.com/assets/13142011/9367117/19c28f04-4681-11e5-80f6-bab52bd77c89.PNG)
Hello, I am needing to provision a server with multiple datastores to use with mountpoints for SQL Server. I have a datastore specificed, and multiple additional_dsk_size_gb: statements in the recipe. However It is just adding one additional datastore. Below is a sample of the recipe. 

Thanks!

with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 2,
  memory_mb: 4096,
  network_name: ["VLAN18"],
  datacenter: 'datacenter name,
  datastore: 'Prod0_Tier1_3PAR01',
  additional_disk_size_gb: 5,
  additional_disk_size_gb: 5,
  additional_disk_size_gb: 5,
  additional_disk_size_gb: 5,
  resource_pool: 'Dev_Cluster_01',

**Comment by mwrock** [comment]
Unfortunately this is currently implemented to just add one disk. Seems like the best approach here would be to allow `additional_disk_size_gb` to take an array of sizes and create as many additinal disks as specified. That should be fairly straight forward to do.

**Comment by bradwilliamson** [comment]
What method would I use if I created an array such as  additional_disk_size_gb: ['5,5,5,5'] ? Would I need to come in and specify an additional_disk_size_gb or multiple datastore options?

**Comment by mwrock** [comment]
was thinking  `additional_disk_size_gb: [5,5,5,5] ` and it could also take just a number and not an array for back compat.

Does that make sense and sound reasonable?

**Comment by bradwilliamson** [comment]
Here is what I have tried and the results of it. 

with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 2,
  memory_mb: 4096,
  network_name: ["VLAN18"],
  datacenter: 'datacenter name,
  datastore: 'Prod0_Tier1_3PAR01',
  additional_disk_size_gb: ['5,5,5,5'],
  resource_pool: 'Dev_Cluster_01',


Getting the following outpout from chef-client 
[2015-08-19T15:03:32-05:00] INFO: Sending resource update report (run-id: 44357506-5c5e-47d1-9fb1-465d38fdac32)
[2015-08-19T15:03:32-05:00] FATAL: NoMethodError: machine[ChefSQLDB01] (vsphere::sqlprov line 52) had an error: NoMethod
od `to_i' for ["5,5,5,5"]:Array

**Comment by mwrock** [comment]
right. This is not implemented yet. Right now you can only add 1 additional disk.

I guess I'm just asking if feeding `additional_disk_size_gb` an array of numbers makes sense before I actually start coding it.

**Comment by bradwilliamson** [comment]
Yeah, that makes sense to me. I appreciate your help on this as always!

**Comment by mwrock** [comment]
This is released in 0.8.0 and an example is added to the readme. I do think that the ideal implementation would be to add disks as a custom resource. I likely won't have cycles to add this as an additional resource for some time so I am releasing this cruder, simpler but working implementation for now.
