### ISSUE TITLE
Virtual Machines provisioned using DHCP result in WinRM timeouts

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#32]
We recently updated to driver 0.8.1 on two of our workstations and we started to notice anytime we use DHCP to provision new servers it results in a WinRM timeout. The servers provisioned actually pull an IP from DHCP but for some reason it seems to attempt to use the 169 during bootstrapping over WinRM.. If we go in and add a static IP the servers provision correctly. I've tried multiple recipes and it seems to fail on all of them now. The examples below are of a machine_batch provision recipe but the same thing happens when provisioning just a one machine resource. 

![dhcp](https://cloud.githubusercontent.com/assets/13142011/9910401/9a3fd62c-5c62-11e5-94b3-ee12d4c5c809.PNG)

![ipobtained](https://cloud.githubusercontent.com/assets/13142011/9910990/9097afe8-5c65-11e5-99c2-5d0c2d63987c.PNG)

![dhcppartofrecipe](https://cloud.githubusercontent.com/assets/13142011/9911024/b2abbe44-5c65-11e5-942c-8bdaa3b1aa9a.PNG)

![winrmfailure2](https://cloud.githubusercontent.com/assets/13142011/9911043/cbc29fa6-5c65-11e5-9f46-c47bd76789f6.PNG)
![winrmfailureendofps](https://cloud.githubusercontent.com/assets/13142011/9911044/cbc421c8-5c65-11e5-942b-306178ad816d.PNG)

**Comment by mwrock** [comment]
Thanks for the detailed report. What version were those machines on before?

**Comment by mwrock** [comment]
So looking over the code, I can see how this could happen if there is a delay in the DHCP lease assignment. The vmware driver in this case will prematurely conclude it has found an ip. I'm guessing we never ran into this at CenturyLink because the DHCP assignment was faster than it took VMWare tools to come up and grab the ip. So either your DHCP assignment is slower or our vmware tools startup was slower.

The driver really should do a final sanity check on the IP and ensure the transport can connect.

I'm no longer at centurylink, but should be able to get access to vmware infra to test a fix. Will keep you posted.

**Comment by bradwilliamson** [comment]
I wan to say it was 0.7.1 .  I did a chef gem version and saw that I had 0.8.0 also installed. I am going back and trying to test to see which one works.

**Comment by bradwilliamson** [comment]
0.8.0 didn't work. It might have never worked now that I think about it. It just became up until recent with provisioning multiple virtual machines that we needed to use DHCP. It might have been that it failed communication over winrm during the initial bootstrap, and then later on the preinstalled chef-client went out and downloaded the runlist from the server finishing it's config. We do have vmware tools preloaded on the template we are using for this running Windows 2012 R2 Server.

**Comment by mwrock** [comment]
I'd really be interested to see if #41 fixes this. I don't have access to an environment where I can test it but if anyone wants to give it a try, 0.8.3.dev has that PR. Please report back results if you do try it.

**Comment by bradwilliamson** [comment]
Hello Matt, I missed the response and just started using 0.8.3.dev.  I am getting a failed chef-client run with the error below It is from my powershell session on the chef workstation. Below it is the stacktrace. It seems to occur if I assign a static IP or attempt to let it grab one from DHCP. If you need any additional logging info let me know. 

Running handlers complete
[2015-12-04T15:33:57-06:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 minutes 41 seconds
[2015-12-04T15:33:57-06:00] INFO: Sending resource update report (run-id: bca6ba81-c82b-44d4-affe-829873378f40)
[2015-12-04T15:33:57-06:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-12-04T15:33:57-06:00] FATAL: NameError: machine[ChefSQLDB103] (vsphere::sqlprov10 line 53) had an error: NameErro
: undefined local variable or method `ip' for #<ChefProvisioningVsphere::VsphereDriver:0x6706578>

Generated at 2015-12-04 15:33:57 -0600
NameError: machine[ChefSQLDB103] (vsphere::sqlprov10 line 53) had an error: NameError: undefined local variable or method `ip' for #<ChefProvisioningVsphere::VsphereDriver:0x6706578>
C:/Users/bradwilliamsonsa/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3.dev/lib/chef/provisioning/vsphere_driver/driver.rb:363:in `wait_for_ip'
C:/Users/bradwilliamsonsa/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3.dev/lib/chef/provisioning/vsphere_driver/driver.rb:307:in `attempt_ip'
C:/Users/bradwilliamsonsa/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3.dev/lib/chef/provisioning/vsphere_driver/driver.rb:274:in `transport_respond?'
C:/Users/bradwilliamsonsa/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3.dev/lib/chef/provisioning/vsphere_driver/driver.rb:209:in `ready_machine'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/provider.rb:362:in `action_ready'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.4.1/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/provider.rb:362:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource.rb:585:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/runner.rb:81:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/runner.rb:80:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:653:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:648:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:648:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:687:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:269:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:388:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/bin/chef-client:65:in `load'
C:/opscode/chefdk/bin/chef-client:65:in `<main>'

**Comment by mwrock** [comment]
ah. that error was fixed but never found its way to rubygems. I just released a new dev gem 0.8.3.dev.2 that includes the fix. The fix worked for others (see #38), hopefully this fixes you as well.

**Comment by bradwilliamson** [comment]
Thanks, I appreciate it! I'll give it a shot Monday.


Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Matt Wrock <notifications@github.com> </div><div>Date: 12/5/2015  11:03 AM  (GMT-06:00) </div><div>To: CenturyLinkCloud/chef-provisioning-vsphere <chef-provisioning-vsphere@noreply.github.com> </div><div>Cc: Brad Williamson <bradtech519@live.com> </div><div>Subject: Re: [chef-provisioning-vsphere] Virtual Machines provisioned using DHCP result in WinRM timeouts (#32) </div><div>
</div>
ah. that error was fixed but never found its way to rubygems. I just released a new dev gem 0.8.3.dev.2 that includes the fix. The fix worked for others (see #38), hopefully this fixes you as well.


---

**Comment by bradwilliamson** [comment]
I can confirm that 0.8.3.dev.2 has resolved provisioning to DHCP.

**Comment by mwrock** [comment]
just released 0.8.3 to rubygems

**Comment by bradwilliamson** [comment]
Thank you Matt appreciate the work very much!
