### ISSUE TITLE
Provision Windows - Network Unreachable

### ISSUE THREAD

**Issue by nwesoccer** [CenturyLinkCloud/chef-provisioning-vsphere#36]
We are provisioning a Windows server with custom specs.  The cloning works, the server is powered on with a disconnected network.  It seems like the customizations are then applied, and the vm is rebooted.  After it restarts, the network in vpshere shows 'connected', after a few seconds the hostname will show in vpshere and the command line will say `wnexttest2 is now ready`, but vpshere shows no ip yet.  The provisioning then fails with `Errno::ENETUNREACH Network is unreachable - connect(2) for "10.200.2.78" port 5985 (http://10.200.2.78:5985)`.  A few seconds later and vpshere shows a 169.x.x.x ip address.  Then, a minute or so later it shows the actual ip address we set in the customization.  A linux provisioning works fine, just this issue with Windows.  Also, once the vm shows the correct ip, if i re-run the provisioning...it will bootstrap it fine.

```
    - creating machine wnexttest2 on vsphere://xxx.net/sdk?use_ssl=true&insecure=true
    -   start_timeout: 600
    -   create_timeout: 600
    -   ready_timeout: 1000
    -   use_linked_clone: false
    -   customization_spec: {:org_name=>"XXX", :time_zone=>"America/New_York", :win_time_zone=>35, :product_id=>"xxxxx-xxxxx-xxxxx-xxxxx-xxxxx", :ipsettings=>{:ip=>"10.200.2.78", :subnetMask=>"255.255.255.0", :gateway=>["10.200.2.1"], :dnsServerList=>["10.200.1.43", "10.200.1.44"]}, :domain=>"local", :hostname=>"wnexttest2"}
    -   ssh: {:paranoid=>false, :user=>"xxx", :password=>"xxx"}
    -   vm_folder: "Dev Env/DevOps/Next"
    -   datacenter: "powerdms.net"
    -   datastore: "vm_vol_1"
    -   resource_pool: "hq"
    -   template_folder: "Templates"
    -   template_name: "win2k12base"   **This is Windows 2012 R2 with all latest updates applied**
    -   network_name: ["VLAN_202_PDMSSvr"]
    -   num_cpus: 2
    -   memory_mb: 4096
    - finding networks...
    - network: VLAN_202_PDMSSvr is a Network
    - changing template nic for VLAN_202_PDMSSvr
    - customizing wnexttest2               with static IP 10.200.2.78
    - customizing wnexttest2 with /
                  dynamic IP and DNS: ["10.200.1.43", "10.200.1.44"]
```

<img width="669" alt="screen shot 2015-09-28 at 3 51 57 pm" src="https://cloud.githubusercontent.com/assets/2534087/10146859/ec500186-65f8-11e5-9d36-f9efed485b66.png">
<img width="454" alt="screen shot 2015-09-28 at 3 45 52 pm" src="https://cloud.githubusercontent.com/assets/2534087/10146747/734cb0fe-65f8-11e5-9bd2-5068dbce32f7.png">
<img width="525" alt="screen shot 2015-09-28 at 3 48 05 pm" src="https://cloud.githubusercontent.com/assets/2534087/10146749/76985470-65f8-11e5-8e20-a039a9830908.png">

Here are my chef gem versions when running `chef gem list`:

```
chef (12.4.1)
chef-config (12.4.1)
chef-dk (0.7.0)
chef-provisioning (1.4.0, 1.3.0)
chef-provisioning-aws (1.3.1)
chef-provisioning-azure (0.3.2)
chef-provisioning-fog (0.13.2)
chef-provisioning-vagrant (0.9.0)
chef-provisioning-vsphere (0.8.1)
chef-vault (2.6.1)
chef-zero (4.2.3, 1.5.6)
```

The template is a Windows 2012 R2 with all the latest updates and the latest VM tools installed.  Is there something else that needs to be setup on the template maybe?

**Comment by nwesoccer** [comment]
I've also tried increasing all 3 timeouts to 2000.

**Comment by mwrock** [comment]
Yes you are probably missing some winrm setup in the template:

```
winrm set winrm/config/client/auth '@{Basic="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
```

**Comment by nwesoccer** [comment]
Sorry, just saw your response.  Seems like the 3 you mentioned are all set correctly.  And like I said, it will work when I re-run the provisioning once the server is created.

<img width="306" alt="screen shot 2015-10-07 at 2 21 37 pm" src="https://cloud.githubusercontent.com/assets/2534087/10346781/dbaf6378-6cfe-11e5-9b44-1c4a0106308c.png">

**Comment by mwrock** [comment]
Hmm. Hard to say why this is. You might try connecting via winrm from a different session during this same time just to see if winrm connectivity is working.

**Comment by nwesoccer** [comment]
This seems to have fixed itself either via an upgrade, we also greatly shrunk our base image size, and made bunch of changes to our vm infrastructure networking.  Either way, thx!
