### ISSUE TITLE
need to specify vmname

### ISSUE THREAD

**Issue by devilldog** [CenturyLinkCloud/chef-provisioning-vsphere#39]
Hi, Is there a way to pass a vm name to the clone process when using the test kitchen driver ?
thanks !
rob

**Comment by mwrock** [comment]
yes. Its `:vsphere_name`

Example:
```
driver_config:
  vsphere_name: 'my_server'
```

**Comment by ricardolupo** [comment]
@mwrock the gem that's available from rubygems is still using an arbitrary ```kitchen-[hexrandomvalue]``` name in the vm config. We need the version that's merged to master released as a gem. I verified this in my own testing to be the case

**Comment by devilldog** [comment]
works w00t! thanks !
