### ISSUE TITLE
VM is provisioned as linked clone when set to false

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#48]
Hello, I provisioned a VM from a recipe that had use_linked_clone: 'false', set within  the recipe.  I then did a VM/Storage Vmotion to our development ESXi hosts which do not have access to the storage of the template we use. The cloned VM wouldn't power on and I began to investigate the issue. I looked at the descriptor file for the vmdk and it has a ParentFilenameHint setting with the parent VMs VMDK referenced. 
![descripterfile](https://cloud.githubusercontent.com/assets/13142011/11695185/7f463016-9e73-11e5-94ec-4452ba0161c4.png)

It appears to be happening regardless if I set use_linked_clone to true or false. 

with_machine_options :bootstrap_options => {
  use_linked_clone: 'False',
  num_cpus: 2,
  memory_mb: 8096,

As you can see in the screenshot above it is referencing W2K12STD2 which is the name of the template we clone from and not the name of the VM itself.

**Comment by robcoward** [comment]
Have you tried not quoting 'False' ? ie.
use_linked_clone: false

'False' != false in the ruby world iirc.

**Comment by bradwilliamson** [comment]
That appears to have been the problem. Thanks Rob!
