### ISSUE TITLE
Machine_batch provisioning issues

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#49]
I apologize ahead of time if I don't word this right. I am attempting to use the machine_batch resource to create two servers. One is a SQL Server that I have 5 recipes written building it out using our standards here which has it's own unique machine_options that I don't want to share with the IIS Server such as the additional_disk_size_gb setting. The second machine is a simple iis server for now that just installs iis. Up until now I have used the with_machine_options boostrap_options  settings and built out one server. I have used machine_batch in the past but with "like" servers 5 IIS servers for example.

There are some settings that could be shared among the sql and iis machines like domain join information so I was going to leave that up in the with_machine_options :bootstrap_options code, and remove unique settings. 

Here is the code I have been attempting to use below the with_machine options. Does this look like something that is doable. I have attached the complete provisioning recipe & errors I'm getting. I've been looking this afternoon at other examples on chef's website & forums but the people seem to be using fog for aws so I'm not sure how much of that translates over. 

machine_batch do
   machine 'sql1' do
 machine_options :bootstrap_options => {
 additional_disk_size_gb: [20,10,5,4],
 num_cpus: 4,
 memory_mb: 16384,
}
  run_list ["recipe[vsphere::sqlmp4]"]
   end
 machine 'web1' do
    machine_options :bootstrap_options => {
  num_cpus: 2,
  memory_mb: 8096,
}
    run_list ["recipe[vsphere::iis]"]

end
end

[error1.txt](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/files/58828/error1.txt)

[redactedrecipe.txt](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/files/58829/redactedrecipe.txt)

**Comment by mwrock** [comment]
I don't think the machine options you add to individual machine resources will be merged with what you have in `with_machine_options`. What you should do is assign the hash you are using in `with_machine_options` to a variable and then inject the individual machine settings for each maching like this:
```
my_options = { big options hash }

machine_batch do
sql_options = my_options.dup
sql_options[:bootstrap_options][:bum_cpus]=4
# other options, etc.

machine 'sql1' do
machine_options sql_options
run_list ["recipe[vsphere::sqlmp4]"]
end

iis_options = my_options.dup
iis_options[:bootstrap_options][:bum_cpus]=2
# other options, etc.

machine 'web1' do
machine_options iis_options
run_list ["recipe[vsphere::iis]"]

end
end
```

**Comment by bradwilliamson** [comment]
Could I use a variable and assign it to a hash inside the machine batch for the sql_options and iis_options variables?  I attempted the below and get 


================================================================================
Error executing action `converge` on resource 'machine_batch[default]'
================================================================================

NoMethodError
-------------


undefined method `[]' for nil:NilClass

Resource Declaration:


Here is a copy of the recipe. 


[recipeexample.txt](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/files/59814/recipeexample.txt)

**Comment by mwrock** [comment]
so looks like you have:
```
sql_options = my_options.dup
sql_options = {
	num_cpus: 8,
  	memory_mb: 16384,
  	additional_disk_size_gb: [20,10,5,4],
  	 }
```
Here the second line will simply replace the hash in the first.

**Comment by bradwilliamson** [comment]
I seem to be still running into issues with using the hash for each machine in the batch. I've went back to the first way of doing it again. Where you have the large hash and assign it to  a variable & use the .dup. Then after that specify individual options for the machine. Does this look like the correct syntax for this to work? 

machine_options = { large hash options
}

machine_batch do
sql_options = machine_options.dup
sql_options = [:bootstrap_options][:num_cpus]=4
[:bootstrap_options][:memory_mb]=16384
[:bootstrap_options][:additional_disk_size_gb]=[20,10,5,4]
machine "ChefSQLDBbatch1" do
  machine_options sql_options
 run_list ["role[sqlinstall]"]
end
iis_options = machine_options.dup
iis_options = [:bootstrap_options][:num_cpus]=2
[:bootstrap_options][:memory_mb]=8096
machine "Chefwebbatch1" do
  machine_options iis_options
  run_list ["recipe[vsphere::iis"]
end
end

I get the following output from my chef workstation in powershell after running the provision recipe.Does anything stand out incorrect? 

PS C:\chef-repo\cookbooks\vsphere> chef-client -o 'vsphere::newbatch1' -c C:\chef-repo\.chef\knife.rb

Starting Chef Client, version 12.5.1
[2015-12-14T16:36:34-06:00] INFO: *** Chef 12.5.1 ***
[2015-12-14T16:36:34-06:00] INFO: Chef-client pid: 2416
[2015-12-14T16:36:46-06:00] WARN: Run List override has been provided.
[2015-12-14T16:36:46-06:00] WARN: Original Run List: []
[2015-12-14T16:36:46-06:00] WARN: Overridden Run List: [recipe[vsphere::newbatch1]]
[2015-12-14T16:36:46-06:00] INFO: Run List is [recipe[vsphere::newbatch1]]
[2015-12-14T16:36:46-06:00] INFO: Run List expands to [vsphere::newbatch1]
[2015-12-14T16:36:46-06:00] INFO: Starting Chef Run for chefadmin
[2015-12-14T16:36:46-06:00] INFO: Running start handlers
[2015-12-14T16:36:46-06:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["vsphere::newbatch1"]
[2015-12-14T16:36:47-06:00] INFO: Loading cookbooks [vsphere@1.0.2]
[2015-12-14T16:36:47-06:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - vsphere (1.0.2)
Compiling Cookbooks...
Recipe: vsphere::newbatch1
  * chef_gem[chef-provisioning-vsphere] action install[2015-12-14T16:36:49-06:00] INFO: Processing chef_gem[chef-provisi
oning-vsphere] action install (vsphere::newbatch1 line 2)
 (up to date)

  ================================================================================
  Recipe Compile Error in C:/chef/cache/cookbooks/vsphere/recipes/newbatch1.rb
  ================================================================================

  TypeError
  ---------
  no implicit conversion of Symbol into Integer


  Running handlers:
[2015-12-14T16:36:57-06:00] ERROR: Running exception handlers
  Running handlers complete
[2015-12-14T16:36:57-06:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 30 seconds
[2015-12-14T16:36:57-06:00] INFO: Sending resource update report (run-id: 6b5f54e1-1461-475d-a5a7-b268c656e71e)
[2015-12-14T16:36:57-06:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-12-14T16:36:57-06:00] FATAL: TypeError: no implicit conversion of Symbol into Integer
PS C:\chef-repo\cookbooks\vsphere>

**Comment by mwrock** [comment]
try 
```
machine_batch do
sql_options = machine_options.dup
sql_options[:bootstrap_options][:num_cpus]=4
sql_options[:bootstrap_options][:memory_mb]=16384
sql_options[:bootstrap_options][:additional_disk_size_gb]=[20,10,5,4]
machine "ChefSQLDBbatch1" do
machine_options sql_options
run_list ["role[sqlinstall]"]
end
iis_options = machine_options.dup
iis_options[:bootstrap_options][:num_cpus]=2
iis_options[:bootstrap_options][:memory_mb]=8096
machine "Chefwebbatch1" do
machine_options iis_options
run_list ["recipe[vsphere::iis"]
end
end
```

**Comment by bradwilliamson** [comment]
That produced a different error. I get the below in powershell. I'lve attached the stacktrace as well



Starting Chef Client, version 12.5.1
[2015-12-14T16:47:32-06:00] INFO: *** Chef 12.5.1 ***
[2015-12-14T16:47:32-06:00] INFO: Chef-client pid: 2464
[2015-12-14T16:47:45-06:00] WARN: Run List override has been provided.
[2015-12-14T16:47:45-06:00] WARN: Original Run List: []
[2015-12-14T16:47:45-06:00] WARN: Overridden Run List: [recipe[vsphere::newbatch1]]
[2015-12-14T16:47:45-06:00] INFO: Run List is [recipe[vsphere::newbatch1]]
[2015-12-14T16:47:45-06:00] INFO: Run List expands to [vsphere::newbatch1]
[2015-12-14T16:47:45-06:00] INFO: Starting Chef Run for chefadmin
[2015-12-14T16:47:45-06:00] INFO: Running start handlers
[2015-12-14T16:47:45-06:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["vsphere::newbatch1"]
[2015-12-14T16:47:45-06:00] INFO: Loading cookbooks [vsphere@1.0.2]
[2015-12-14T16:47:45-06:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - vsphere (1.0.2)
Compiling Cookbooks...
Recipe: vsphere::newbatch1
  * chef_gem[chef-provisioning-vsphere] action install[2015-12-14T16:47:47-06:00] INFO: Processing chef_gem[chef-provisi
oning-vsphere] action install (vsphere::newbatch1 line 2)
 (up to date)

  ================================================================================
  Recipe Compile Error in C:/chef/cache/cookbooks/vsphere/recipes/newbatch1.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `[]=' for nil:NilClass


  Running handlers:
[2015-12-14T16:47:56-06:00] ERROR: Running exception handlers
  Running handlers complete
[2015-12-14T16:47:56-06:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 31 seconds
[2015-12-14T16:47:56-06:00] INFO: Sending resource update report (run-id: 1013dec6-b262-45a6-9db0-92388e47e05f)
[2015-12-14T16:47:56-06:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-12-14T16:47:56-06:00] FATAL: NoMethodError: undefined method `[]=' for nil:NilClass
PS C:\chef-repo\cookbooks\vsphere>





[stacktrace.txt](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/files/61856/stacktrace.txt)

**Comment by mwrock** [comment]
does `machine_options` have a `:bootstrap_options` key?

**Comment by bradwilliamson** [comment]
No, should I include it?

here is the machine_options code

  machine_options = {
  use_linked_clone: false,
  network_name: ["VLAN168"],
  datacenter: 'OSCN',
  datastore: '3PAR01',
  resource_pool: 'OSCN_Production_Cluster_01',
  vm_folder: 'Organizational Units/DEVOPS',
  template_name: 'W2K12STD2',
  customization_spec: {
     ipsettings: {
    gateway: ["10.100.168.1"],  
    dnsServerList: ['10.100.168.20'],
  
    },
    :domain => 'OSCNDEVOPS.net',
  :win_time_zone => '020',
  :domainAdmin => "Chefdomainjoin",
  :domainAdminPassword => "AAAAAAAAAAAAAAAAA",
  :org_name => 'OSCN',
  :product_id => 'AAAAAAAAAAAAAAAAAAA',
    
  }, 
  :ssh => {
    :user => 'administrator',
    :password => 'AAAAAAAAAAAAAAAA',
    :paranoid => false,
  },

:convergence_options => {
  :ssl_verify_mode => :verify_none
},

**Comment by mwrock** [comment]
Yeah. You want `machine_options` to have the same basic structure as the hash given to `with_machine_options`.

**Comment by bradwilliamson** [comment]
Thanks, I think that might have got it to work. I'll be able to verify later tonight or tomorrow morning. I added 

machine_options = {
:boostrap_options => { 

and modifiable closing braces to the machine_options hash. It's completed to the part of cloning off the template. I Appreciate all the help Matt.

**Comment by bradwilliamson** [comment]
It seems to run without any syntax errors now. However in the machine_batch below

**Comment by bradwilliamson** [comment]
Matt,

Wanted to update you on this. I added another variable = {hash} with the same similiar settings I wanted shared. That seemed to fix the problem I was having in the post above. When I did that the iis server stopped getting the additional_disk_size_gb & the CPU/Memory settings stopped being 2 CPU, 8GB RAM on both servers. 

large_options = {
Common shared settings
}
large_options1 =  {
Same Common shared settings above 
}

machine_batch do
sql_options = large_options.dup
sql_options[:bootstrap_options][:num_cpus]=4
sql_options[:bootstrap_options][:memory_mb]=16384
sql_options[:bootstrap_options][:additional_disk_size_gb]=[20,10,5,4]
machine "ChefSQLDBbatch1" do
machine_options sql_options
run_list ["recipe[vsphere::sqlmp4]"]
end

iis_options = large_options2.dup
iis_options[:bootstrap_options][:num_cpus]=2
iis_options[:bootstrap_options][:memory_mb]=8096
machine "Chefwebbatch1" do
machine_options iis_options
run_list ["recipe[vsphere::iis]"]
end
end

**Comment by adabalaravi** [comment]
I have a requirement to provision multiple servers parallel on vshpere, can any one help me out on this

**Comment by bradwilliamson** [comment]
> I have a requirement to provision multiple servers parallel on vshpere, can any one help me out on this

https://github.com/chef/chef-provisioning

The link above is where this project is currently maintained.  They have some examples.  The code above also should help if you need to build batches of dissimilar VMs.
