### ISSUE TITLE
 RbVmomi::Fault: InvalidArgument: A specified parameter was not correct. spec.identity.hostName

### ISSUE THREAD

**Issue by sencha7** [CenturyLinkCloud/chef-provisioning-vsphere#5]
Hello,

I am trying to test out provisioning using vCenter. It's probably something I'm doing wrong, but I thought I'd see if someone can help. I am using chef-zero. 
I am able to provision a VM but customization spec (P address, Gateway, dnsserverlist and etc) not applied/set on the VM and getting below error. 

Error message:
> RbVmomi::Fault: InvalidArgument: A specified parameter was not correct.
>spec.identity.hostName

Recipe :
>with_machine_options :bootstrap_options => {
  num_cpus: 2,
  memory_mb: 4096,
  network_name: ["VM Network"],
  datacenter: 'IB',
  resource_pool: '172.26.1.4',
  template_name: 'redhat',
  hostname: "chef.demo.com",
  customization_spec: {
    ipsettings: {
      ip: '172.26.1.101',
      dnsServerList: ['172.26.1.2'],
      subnetMask: '255.255.255.0',
      gateway: ['172.26.1.1']
    },
    :domain => 'demo.com'
  },
  :ssh => {
    :user => 'root',
    :password => 'password',
    :paranoid => false,
  }
}

Stack trace :
`Generated at 2015-06-16 22:06:50 -0700
RbVmomi::Fault: machine[chef_server] (infoblox::chef_provision line 41) had an error: RbVmomi::Fault: InvalidArgument: A specified parameter was not correct. 
spec.identity.hostName
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7/lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb:173:in `do_vm_clone'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7/lib/chef/provisioning/vsphere_driver/driver.rb:494:in `clone_vm'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:30:in `block in <class:Machine>'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:37:in `block in <class:Machine>'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:55:in `block in <class:Machine>'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
c:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
c:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/bin/chef-client:63:in `load'
c:/opscode/chef/bin/chef-client:63:in `<main>'`

**Comment by sencha7** [comment]
I also tried with without `hostname` key but getting same error.

**Comment by mwrock** [comment]
Try removing the domain fom the hostname so that hostname is simply 'chef'.

**Comment by sencha7** [comment]
@mwrock 
Got same error again.

**Comment by mwrock** [comment]
hmm. Could you `gem install chef-provisioning-vsphere -v '0.5.7.dev6'`

And then run your recipe with debug verbosity and post a link to the emitted clone_spec output in the debug logging? (removing secrets)

That would be super helpful to troubleshoot this.

Thanks!

**Comment by sencha7** [comment]
@mwrock  Please find the debug log :

>[2015-06-17T00:00:55-07:00] DEBUG: Finding pool: 172.26.1.4
[2015-06-17T00:00:55-07:00] DEBUG: Identifying entity part: 172.26.1.4 in folder type: Folder
[2015-06-17T00:00:55-07:00] DEBUG: Parent folder is a folder
[2015-06-17T00:00:56-07:00] DEBUG: Clone spec: VirtualMachineCloneSpec(
  config: VirtualMachineConfigSpec(
    annotation: nil,
    cpuHotAddEnabled: true,
    cpuHotRemoveEnabled: true,
    deviceChange: [VirtualDeviceConfigSpec(
       device: VirtualVmxnet3(
         backing: VirtualEthernetCardNetworkBackingInfo(
           deviceName: "VM Network"
         ),
         connectable: VirtualDeviceConnectInfo(
           allowGuestControl: true,
           connected: true,
           startConnected: true
         ),
         deviceInfo: Description( label: "Ethernet 1", summary: "VM Network" ),
         key: 4000
       ),
       operation: #<VirtualDeviceConfigSpecOperation:0x5f672d0 @value="edit">
     )],
    memoryHotAddEnabled: true,
    memoryMB: 4096,
    numCPUs: 2
  ),
  customization: CustomizationSpec(
    globalIPSettings: CustomizationGlobalIPSettings(
      dnsServerList: ["172.26.1.2"],
      dnsSuffixList: ["demo.com"]
    ),
    identity: CustomizationLinuxPrep(
      domain: "demo.com",
      hostName: CustomizationFixedName( name: "chef_server02" ),
      hwClockUTC: nil,
      timeZone: nil
    ),
    nicSettingMap: [CustomizationAdapterMapping(
       adapter: CustomizationIPSettings(
         dnsDomain: "demo.com",
         dnsServerList: ["172.26.1.2"],
         gateway: ["172.26.1.1"],
         ip: CustomizationFixedIp( ipAddress: "172.26.1.101" ),
         subnetMask: "255.255.255.0"
       )
     )]
  ),
  location: VirtualMachineRelocateSpec(
    datastore: Datastore("datastore-10"),
    pool: ResourcePool("resgroup-8")
  ),
  powerOn: false,
  template: false
)

[2015-06-17T00:07:08-07:00] INFO: Running queued delayed notifications before re-raising exception
[2015-06-17T00:07:08-07:00] DEBUG: Re-raising exception: RbVmomi::Fault - machine[chef_server02] (infoblox::chef_provision line 42) had an error: RbVmomi::Fault: InvalidArgument: A specified parameter was not correct. 
spec.identity.hostName
c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7.dev6/lib/chef/provisioning/vsphere_driver/driver.rb:505:in `clone_vm'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7.dev6/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-vsphere-0.5.7.dev6/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:30:in `block in <class:Machine>'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:37:in `block in <class:Machine>'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  c:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:55:in `block in <class:Machine>'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  c:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
  c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  c:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  c:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
  c:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  c:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  c:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  c:/opscode/chef/bin/chef-client:63:in `load'
  c:/opscode/chef/bin/chef-client:63:in `<main>'
[2015-06-17T00:07:08-07:00] ERROR: Running exception handlers
[2015-06-17T00:07:08-07:00] ERROR: Exception handlers complete
[2015-06-17T00:07:08-07:00] FATAL: Stacktrace dumped to c:/Users/rdp/Desktop/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out

**Comment by mwrock** [comment]
Hmm. Looks like the problem is the underscore in the host name. I've seen this happen a few times on our own provisionings too. We should add some error handling to match the restrictions vmware places on hostnames. I dont have them on hand but I'm hoping to find them documented.

You had `chef` in your previous message but I'm guessing the missing `_servero2` was an oversight in pasting to this issue?

**Comment by sencha7** [comment]
I have tried with `_` (underscore) but getting same error.

**Comment by mwrock** [comment]
Yeah. I'm saying it is the underscore that is the problem. So it sounds like you see problems without the underscore as well? Mind running the dev gem (0.5.7.dev6) with debug verbosity and include the clone_spec output? Thanks!

**Comment by sencha7** [comment]
@mwrock 
Sorry it was my bad.
Now I am able to run it successfully. I did small change in customization spec, removed the hostname from customization spec and changed the name of machine resource to alphabetic (without underscore) and it run.
Thanx

**Comment by mwrock** [comment]
Sounds good. Keeping open to add proper exception handling.
