### ISSUE TITLE
plaintext passwords

### ISSUE THREAD

**Issue by rj-reilly** [CenturyLinkCloud/chef-provisioning-vsphere#52]
What options are there for not providing the vsphere credentials in plan text ?

**Comment by mwrock** [comment]
You can use a secrets manager/vault to manage the credentials. Thats not build into the driver but you would use it externally to grab the credentials and then pass them to the driver. They get sent to vsphere over SSL.

**Comment by devilldog** [comment]
Yeah my concern is more about the cress being written plain text to disk of
can they passed to kitchen on the command line so they are out written to
disk

**Comment by mwrock** [comment]
Hmm. Yeah I see what you mean. For Kitchen I used a dev vsphere environment where anyone who had access to the repo also had the credentials but that does not work for everyone.

**Comment by devilldog** [comment]
That is what we are leaning to as well, plus encrypting the creds at rest on the jenkins server and render a .kitchen.yml template with the creds, dump all of kitchen create to /dev/null and then remove the files when the job is complete success or failure, but there will still be a time that the creds are plain text on disk but at least it will just be for the test vsphere.

**Comment by justindossey** [comment]
I pulled the creds from a gpg-encrypted file, set them in the environment, then referred to them from .kitchen.yml via ERB (e.g. `<%= ENV['VSPHERE_USERNAME'] %>`).  Creds weren't written in plaintext to disk, and the environment isn't visible to anyone except root and me.

**Comment by bradwilliamson** [comment]
@justindossey Is the encrypted file a cookbook_file or a file on local disk?  I am looking into removing vSphere credentials and local admin/domain admin passwords from provisioning recipes as well. I've been looking into chef-vault an encrypted databags. Would be on a Windows Chef Workstation.

**Comment by justindossey** [comment]
It's a file on local disk-- multi-user system, each person has his own credential file.  You could totally move host credentials (if you're using them) to encrypted data bag, but if you're authenticating vsphere to AD or something, I think it's better to make each person responsible for his own credentials.  I'm doing this on Linux, so you'll need to work out the details of how to decrypt a file (prompting for passphrase if necessary) and evaluate it in the current shell context, then pass the variables along to `kitchen` or `chef-client`.

**Comment by devilldog** [comment]
@bradwilliamson we encrypt ar rest render as a template then shred the file but i like the idea of making it a env var

**Comment by devilldog** [comment]
the problem is, the password will still be printed in the log and if you
jenkins that password is now an artifact of that run, kitchen or the driver
needs to mask the password...

On Thu, May 5, 2016 at 11:08 PM, Justin Dossey <notifications@github.com>
wrote:

> It's a file on local disk-- multi-user system, each person has his own
> credential file. You could totally move host credentials (if you're using
> them) to encrypted data bag, but if you're authenticating vsphere to AD or
> something, I think it's better to make each person responsible for his own
> credentials. I'm doing this on Linux, so you'll need to work out the
> details of how to decrypt a file (prompting for passphrase if necessary)
> and evaluate it in the current shell context, then pass the variables along
> to kitchen or chef-client.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/issues/52#issuecomment-217338205>
>



-- 

Robert Reilly
203 297 3653

**Comment by akulbe** [comment]
Is there support for using SSH keys, rather than passwords?

**Comment by joshk0** [comment]
@akulbe It would be possible but require some coding.

- derive public key from private key
- encrypt password with public key and base64 encode it into config.yml
- when password is required, interact with an SSH-agent to retrieve the private key to decrypt the bytes. If necessary, the agent UI will prompt the user for the passphrase.
- plaintext password is decrypted to memory and can be used to connect to vsphere

IMHO, it's probably less effort to just allow the provisioner to prompt for the password when it needs it. Then it can remember it during the session. Alternatively, can config.yml store a [SAML token](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/338ffa03-f04b-469c-9d71-4071f3948c0e/84b7d0ca-ab70-4e07-b4bd-4caf8f9745d7/doc/PG_Client_App.5.3.html) from vSphere and refresh it when necessary?

**Comment by rj-reilly** [comment]
FYI, There was a PR a few months back that now prevents the password from being printed in the log
