### ISSUE TITLE
Add network card

### ISSUE THREAD

**Issue by mlckha** [CenturyLinkCloud/chef-provisioning-vsphere#53]
Hello,
I would like to add a NIC during provisioning. However, I do not find the solution.
Thanks for your help,
good night

**Comment by mwrock** [comment]
the `:network_name` bootstrap option can be an array of networks.

**Comment by mlckha** [comment]
Hii mwrock, thank's for you fast reply !

Yes, i tried this boostrap option but i don't understand how use it. Can you give me a example ? :)

Thank you,
Regards,

**Comment by mwrock** [comment]
my apologies for the delay. The readme has a few examples of setting up a single network. Here is a modified `bootstrap_options` hash that would create an additional NIC:
```
with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 2,
  memory_mb: 4096,
  network_name: ["vlan_20_172.21.20", "vlan_20_172.22.20"],
  datacenter: 'datacenter_name',
  resource_pool: 'cluster',
  template_name: 'path to template',
  customization_spec: {
    ipsettings: {
      dnsServerList: ['1.2.3.31','1.2.3.41']
    },
    :domain => 'local'
  }
  :ssh => {
    :user => 'root',
    :password => 'password',
    :paranoid => false,
  }
}
```
Note how the `network_name` has an additional element.
