### ISSUE TITLE
Windows 2012 R2 Kitchen cspec

### ISSUE THREAD

**Issue by daryn-kerr** [CenturyLinkCloud/chef-provisioning-vsphere#58]
Hey,

Does anyone know of a way to use an existing vsphere customisation to do the sysprep/domain config of a kitchen virtual machine?

i keep running into this issue and i'm pretty sure if I can get around the domain join then this would be resolve!

>        Finished creating <Kitchen-windows-2012r2> (1m35.05s).
-----> Converging <Kitchen-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.1.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError>)
       [WinRM] connection failed, retrying in 1 seconds (#<WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError>)
$$$$$$ [WinRM] connection failed, terminating (#<WinRM::WinRMAuthorizationError: WinRM::WinRMAuthorizationError>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [WinRM::WinRMAuthorizationError]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by daryn-kerr** [comment]
sry didn't mean to close this!

**Comment by mwrock** [comment]
Are you saying that you think the winrm connection is failing because the instance is not joining to the domain? Are you setting the domain in the `kitchen.yml`?

**Comment by daryn-kerr** [comment]
thanks for your reply Mat i genuinely appreciate it, i actually managed to get this working yesterday after a fair amount of trial and error. seems my 2012 template was what was stopping the wimrm getting through!
