### ISSUE TITLE
Support multi-threading in kitchen testing

### ISSUE THREAD

**Issue by tyler-ball** [CenturyLinkCloud/chef-provisioning-vsphere#6]
Moving https://github.com/test-kitchen/test-kitchen/issues/710 to here for the appropriate fix.  Test Kitchen already exposes multiple ways of locking on a mutex to ensure each Test Kitchen instance doesn't wreck other instances when they need to share context.

There is a pre-create hook that could be used, but that method is called on every kitchen action.  So adding it there would make `kitchen list` spin up a chef-zero server.

So instead we recommend updating the `with_provisioning_driver` method (in a mutex) start up a chef-zero server if one doesn't exist yet:

```ruby
def with_provisioning_driver(name, &block)
  instance.mutexes[self.class].synchronize do
    if @@chef_zero_server.nil?
      Chef::Config.local_mode = true
      Chef::Config.chef_repo_path = Chef::Config.find_chef_repo_path(Dir.pwd)
      require 'chef/local_mode'
      Chef::LocalMode.setup_server_connectivity
      @@chef_zero_server = true
    end
  end
  
  chef_server = Cheffish.default_chef_server
  config[:machine_options][:convergence_options] = {:chef_server => chef_server}
  machine_spec = Chef::Provisioning.chef_managed_entry_store(chef_server).new_entry(:machine, name)
  url = URI::VsphereUrl.from_config(@config[:driver_options]).to_s
  driver = Chef::Provisioning.driver_for_url(url, config)
  action_handler = Chef::Provisioning::ActionHandler.new
  block.call(action_handler, driver, machine_spec)

end
```

Because this is missing some of [the checks](https://github.com/chef/cheffish/blob/v1.2/lib/cheffish.rb#L56-L77) in `Cheffish.honor_local_mode` it will only work with recent versions of `chef`.  If using the latest ChefDK, this should not be an issue.

When we get a new release of `chef-zero` out that has support for `Chef::LocalMode.with_server_connectivity` that can run without a block, we will be able to run `Cheffish.honor_local_mode` inside the Kitchen mutex and will shrink this code quite a lot.  Then this vsphere driver would just need to ensure it is using the latest version of chef-zero.

**Comment by tyler-ball** [comment]
@mwrock let me know if this makes sense (along with my [comment](https://github.com/test-kitchen/test-kitchen/issues/710#issuecomment-114207027)).  Do you agree that this is the right change now to support `kitchen -c` functionality?

**Comment by fnichol** [comment]
So……if you need a mutex for only `Kitchen::Driver::Vsphere` driver instances, you could use:

```ruby
def with_provisioning_driver(name, &block)
  instance.class.mutexes[self.class].synchronize do
    # ...
  end
end
```

Now, that's not the most elegant code, but these are around for Drivers that aren't totally threadsafe in `#create` and `#destroy`. This allows Driver authors to say:

```ruby
module Kitchen
  module Driver
    class Vsphere < Kitchen::Driver::Base
      no_parallel_for :create, :destroy
    end
  end
end
```

**Comment by mwrock** [comment]
Thanks for looking @tyler-ball  and @fnichol!  this all sounds reasonable. I'll play with it and let you know how it goes. Would be nice to support `-c`.

**Comment by mwrock** [comment]
Thanks again guys. This works great. The only gotcha was since I am not excluding any of the driver methods from paralelization, the instance mutex hash was not initialized. So I just added:

```
      def vsphere_mutex
        @@vsphere_mutex ||= begin
          Kitchen.mutex.synchronize do
            instance.class.mutexes ||= Hash.new
            instance.class.mutexes[self.class] = Mutex.new
          end

          instance.class.mutexes[self.class]
        end
      end
```
