### ISSUE TITLE
Provisioning Windows Machine not in an AD domain

### ISSUE THREAD

**Issue by bradwilliamson** [CenturyLinkCloud/chef-provisioning-vsphere#71]
I was curious if the functionality of provisioning non-domain Windows machines would be difficult to do?  I have attempted to remove the domain portion & it is required I believe. This idea came from possibly provisioning a machine & making it the 1st DC in a new AD Forest in a development environment. We had created a new dev enviornment on vlan. I was looking at using the TAMUArch/cookbook.windows_ad possibly to do this. 

  ArgumentError
  -------------
  domain is required

  Resource Declaration:
  ---------------------
  # In C:/chef/cache/cookbooks/vsphere/recipes/nodomain.rb

**Comment by mwrock** [comment]
It is possible but how its done is kind of terrible. (I just got access to some vsphere and can now start submitting some PRs to fix/clean up)

So you just need to set the domain name to `local`. I don't like that because its really "linuxy" and therefore not very discoverable to a windows admin. I'd like to just have it allow no domain being set.

**Comment by bradwilliamson** [comment]
That worked for me.   I was curious if anything during the provisioning phase of a VM is reliant upon functioning DNS?  Provisioning into a VLAN with no DNS functioning currently. Same recipe works in a different vlan but running into issues in this one.

**Comment by mwrock** [comment]
Should not be assuming you are not counting convergence as part of provisioning.

You can also set the DNS servers ini your config settings to a reachable DNS server if you need to.

**Comment by bradwilliamson** [comment]
Thanks, I believe I am facing an ACL issue reaching back to the chef server via 443. I have everything hard coded by IP to connect back to the chef server. Just wanted to rule that out.  I will close the ticket. Thank you @mwrock
