### ISSUE TITLE
How to explicitly set IP address when doing machine_batch

### ISSUE THREAD

**Issue by ktlim86** [CenturyLinkCloud/chef-provisioning-vsphere#73]
Hi,

I have a problem when I want to do a machine_batch to set the IP address explicitly.
This is my recipe.

```
#
# Cookbook Name:: setup_vm
# Recipe:: default
#
# Copyright 2016, YOUR_COMPANY_NAME
#
# All rights reserved - Do Not Redistribute
#
# Reference: https://github.com/CenturyLinkCloud/chef-provisioning-vsphere#kitchen-driver
require 'chef/provisioning'
require 'chef/provisioning/vsphere_driver'

elastic_version = "v1"

chef_gem 'chef-provisioning-vsphere' do
  action :install
  compile_time true
end

with_vsphere_driver host: 'VCENTER_IP',
  insecure: true,
  user:     'VCENTER_USER',
  password: 'VCENTER_PASSWORD'

=begin
# This portion is working.
# Bulk Comment
with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 4,
  host: 'ESXI_HOST',
  memory_mb: 4096,
  network_name: ["MY_INTERNET"],
  datastore: "MY_DATASTORE",
  datacenter: 'MY_DATACENTER',
  template_name: 'VM_TEMPLATE',
  customization_spec: {
    ipsettings: {
      subnetMask: 'MY_SUBNET_MASK',
      gateway: ["MY_GATEWAY"],
      dnsServerList: ['DNS1','DNS2']
    },
    win_time_zone: 215,
    domain: 'local',
    org_name: 'my_org',
    product_id: ''
  },
  :ssh => {
    :user => 'PROVISION_VM_USERNAME',
    :password => 'PROVISION_VM_PASSWORD',
    :paranoid => false,
  }
},
convergence_options: {
  ssl_verify_mode: :verify_none,
  install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
}

machine_batch do
  1.upto(3) do |i|
    machine "server#{i}p" do
      run_list ['setup_vm::reset_winrm','setup_vm::install_python']
    end
  end
end
=end


with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 4,
  host: 'ESXI_HOST',
  memory_mb: 4096,
  network_name: ["MY_INTERNET"],
  datastore: "MY_DATASTORE",
  datacenter: 'MY_DATACENTER',
  template_name: 'VM_TEMPLATE',
  customization_spec: {
    ipsettings: {
      subnetMask: 'MY_SUBNET_MASK',
      gateway: ["MY_GATEWAY"],
      dnsServerList: ['DNS1','DNS2']
    },
    win_time_zone: 215,
    domain: 'local',
    org_name: 'my_org',
    product_id: ''
  },
  :ssh => {
    :user => 'PROVISION_VM_USERNAME',
    :password => 'PROVISION_VM_PASSWORD',
    :paranoid => false,
  }
},
convergence_options: {
  ssl_verify_mode: :verify_none,
  install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
}

machine_batch do
  1.upto(3) do |i|
    machine "server_#{elastic_version}_0#{i}p" do
      machine_options :bootstrap_options => {
        customization_spec: {
          ipsettings: {
            ip: "10.1.1.1#{i}"
          }
        },
        hostname: "server-#{elastic_version}-0#{i}p"
      }
      run_list ['setup_vm::reset_winrm','setup_vm::install_python']
    end
  end
end
```

This is the chef-stacktrace.out.
```
Generated at 2016-04-20 16:06:20 +0800
RuntimeError: machine_batch[default] (setup_vm::setup_elasticsearch line 100) had an error: RuntimeError: missing required parameter name
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:49:in `block (2 levels) in emit_request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:42:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:42:in `block in emit_request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:40:in `emit_request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:83:in `block in call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:71:in `block (2 levels) in soap_envelope'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:70:in `block in soap_envelope'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:64:in `soap_envelope'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:82:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Folder.rb:7:in `find'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb:39:in `find_vm'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:557:in `vm_template_for'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:504:in `clone_vm'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.7.0/lib/chef/provisioning/driver.rb:241:in `block in allocate_machines'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer.rb:93:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

Thanks.

**Comment by mwrock** [comment]
Looks like in your second `machine_batch` you are overwritting the machine_options with a hash that only contains an ip address. So its not able to find the template vm because there is no template vm name.

**Comment by ktlim86** [comment]
Hi mwrock,

Thanks for your quick reply! I would like to ask how do I modify the code to just change the IP address dynamically? I am not too familiar with Ruby.

**Comment by ktlim86** [comment]
Hi mwrock,

I managed to solve it by putting the machine_options into machine resource like this.
```
machine_batch do
  1.upto(3) do |i|
    machine "server_#{elastic_version}_0#{i}p" do
      machine_options :bootstrap_options => {
        use_linked_clone: true,
        num_cpus: 4,
        host: 'ESXI_HOST',
        memory_mb: 4096,
        network_name: ["MY_INTERNET"],
        datastore: "MY_DATASTORE",
        datacenter: 'MY_DATACENTER',
        template_name: 'VM_TEMPLATE',
        customization_spec: {
           ipsettings: {
              ip: "10.1.1.1#{i}"
              subnetMask: 'MY_SUBNET_MASK',
              gateway: ["MY_GATEWAY"],
              dnsServerList: ['DNS1','DNS2']
          },
         win_time_zone: 215,
         domain: 'local',
         org_name: 'my_org',
         product_id: ''
       },
       :ssh => {
          :user => 'PROVISION_VM_USERNAME',
          :password => 'PROVISION_VM_PASSWORD',
          :paranoid => false,
       }
     },
     convergence_options: {
        ssl_verify_mode: :verify_none,
        install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
     }
      run_list ['setup_vm::reset_winrm','setup_vm::install_python']
    end
  end
end
```

**Comment by mwrock** [comment]
oh yes that works. You could also assign the hash to a variable outside the resource:
```
options = { :bootstrap_options => {
        use_linked_clone: true,
        num_cpus: 4,
        host: 'ESXI_HOST',
        memory_mb: 4096,
        network_name: ["MY_INTERNET"],
        datastore: "MY_DATASTORE",
        datacenter: 'MY_DATACENTER',
        template_name: 'VM_TEMPLATE',
        customization_spec: {
           ipsettings: {
              ip: "10.1.1.1#{i}"
              subnetMask: 'MY_SUBNET_MASK',
              gateway: ["MY_GATEWAY"],
              dnsServerList: ['DNS1','DNS2']
          },
         win_time_zone: 215,
         domain: 'local',
         org_name: 'my_org',
         product_id: ''
       },
       :ssh => {
          :user => 'PROVISION_VM_USERNAME',
          :password => 'PROVISION_VM_PASSWORD',
          :paranoid => false,
       }
     },
     convergence_options: {
        ssl_verify_mode: :verify_none,
        install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
     }
}
```
and then dupe and alter for each machine:
```
machine_batch do
  1.upto(3) do |i|
    mopts = options.dup
    mopts[:bootstrap_options][:customization_spec][:ipsettings][:ip]="blah"
    machine "server#{i}p" do
      machine_options mopts
      run_list ['setup_vm::reset_winrm','setup_vm::install_python']
    end
  end
end
```

**Comment by ktlim86** [comment]
Hi mwrock,

Thanks you for your quick reply! I appreciate it! :)

**Comment by adabalaravi** [comment]
> Hi,
> 
> I have a problem when I want to do a machine_batch to set the IP address explicitly.
> This is my recipe.
> 
> ```
> #
> # Cookbook Name:: setup_vm
> # Recipe:: default
> #
> # Copyright 2016, YOUR_COMPANY_NAME
> #
> # All rights reserved - Do Not Redistribute
> #
> # Reference: https://github.com/CenturyLinkCloud/chef-provisioning-vsphere#kitchen-driver
> require 'chef/provisioning'
> require 'chef/provisioning/vsphere_driver'
> 
> elastic_version = "v1"
> 
> chef_gem 'chef-provisioning-vsphere' do
>   action :install
>   compile_time true
> end
> 
> with_vsphere_driver host: 'VCENTER_IP',
>   insecure: true,
>   user:     'VCENTER_USER',
>   password: 'VCENTER_PASSWORD'
> 
> =begin
> # This portion is working.
> # Bulk Comment
> with_machine_options :bootstrap_options => {
>   use_linked_clone: true,
>   num_cpus: 4,
>   host: 'ESXI_HOST',
>   memory_mb: 4096,
>   network_name: ["MY_INTERNET"],
>   datastore: "MY_DATASTORE",
>   datacenter: 'MY_DATACENTER',
>   template_name: 'VM_TEMPLATE',
>   customization_spec: {
>     ipsettings: {
>       subnetMask: 'MY_SUBNET_MASK',
>       gateway: ["MY_GATEWAY"],
>       dnsServerList: ['DNS1','DNS2']
>     },
>     win_time_zone: 215,
>     domain: 'local',
>     org_name: 'my_org',
>     product_id: ''
>   },
>   :ssh => {
>     :user => 'PROVISION_VM_USERNAME',
>     :password => 'PROVISION_VM_PASSWORD',
>     :paranoid => false,
>   }
> },
> convergence_options: {
>   ssl_verify_mode: :verify_none,
>   install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
> }
> 
> machine_batch do
>   1.upto(3) do |i|
>     machine "server#{i}p" do
>       run_list ['setup_vm::reset_winrm','setup_vm::install_python']
>     end
>   end
> end
> =end
> 
> 
> with_machine_options :bootstrap_options => {
>   use_linked_clone: true,
>   num_cpus: 4,
>   host: 'ESXI_HOST',
>   memory_mb: 4096,
>   network_name: ["MY_INTERNET"],
>   datastore: "MY_DATASTORE",
>   datacenter: 'MY_DATACENTER',
>   template_name: 'VM_TEMPLATE',
>   customization_spec: {
>     ipsettings: {
>       subnetMask: 'MY_SUBNET_MASK',
>       gateway: ["MY_GATEWAY"],
>       dnsServerList: ['DNS1','DNS2']
>     },
>     win_time_zone: 215,
>     domain: 'local',
>     org_name: 'my_org',
>     product_id: ''
>   },
>   :ssh => {
>     :user => 'PROVISION_VM_USERNAME',
>     :password => 'PROVISION_VM_PASSWORD',
>     :paranoid => false,
>   }
> },
> convergence_options: {
>   ssl_verify_mode: :verify_none,
>   install_msi_url: "file:///PATH_TO_CHEF_INSTALLER/chef-client-12.8.1-1-x64.msi"
> }
> 
> machine_batch do
>   1.upto(3) do |i|
>     machine "server_#{elastic_version}_0#{i}p" do
>       machine_options :bootstrap_options => {
>         customization_spec: {
>           ipsettings: {
>             ip: "10.1.1.1#{i}"
>           }
>         },
>         hostname: "server-#{elastic_version}-0#{i}p"
>       }
>       run_list ['setup_vm::reset_winrm','setup_vm::install_python']
>     end
>   end
> end
> ```
> 
> This is the chef-stacktrace.out.
> 
> ```
> Generated at 2016-04-20 16:06:20 +0800
> RuntimeError: machine_batch[default] (setup_vm::setup_elasticsearch line 100) had an error: RuntimeError: missing required parameter name
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:49:in `block (2 levels) in emit_request'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:42:in `each'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:42:in `block in emit_request'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:40:in `emit_request'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:83:in `block in call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:71:in `block (2 levels) in soap_envelope'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:70:in `block in soap_envelope'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:64:in `soap_envelope'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:82:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Folder.rb:7:in `find'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/vsphere_helpers.rb:39:in `find_vm'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:557:in `vm_template_for'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:504:in `clone_vm'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
> C:/Users/Administrator/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.7.0/lib/chef/provisioning/driver.rb:241:in `block in allocate_machines'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer.rb:93:in `call'
> C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
> ```
> 
> Thanks.

HI Ktlim,

I like you example, 
I need a help, to provision multiple vm on vsphere using chef vsphere provisioning using machine_batch parallel, Could you please help me out how to implement this/or can you provide any example.
