### ISSUE TITLE
Closed network  problems(:ready works, :setup fails)

### ISSUE THREAD

**Issue by paveljeloudovski** [CenturyLinkCloud/chef-provisioning-vsphere#78]
Ohai, 
I'm working in an environment with no internet connection
Doing :allocate and :ready for machines works 100%. 

However it fails when trying to do a :setup action.

The part where it creates and copies the client.pem and client.rb to the provisioned node succeeds.
Despite providing the [:convergence_options][:install_sh_url] with a value of a local install script url,
the run fails because it's trying to download the package from chef.io. 
Looking at [https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/issues/44](url) it seems that this option is no longer used. 

Any Ideas on how to force using a local URL for the package installation?

Thanks in advance.

**Comment by mwrock** [comment]
this driver really doesn't do anything with  `:install_sh_url`. Thats in the core chef-provisioning driver. It looks like it uses this url as the `omnibus_url` (https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb#L42). That should be the url to an install.sh script used to download the chef client.

**Comment by paveljeloudovski** [comment]
If I understand the code correctly it assignes the omnibus_url the value of install_sh_url.
The problem I see is that it's still trying to access a resource on the internet during the chef client installation phase, and fails since it's a closed network.
Any ideas? I'd really like to get this working properly.

I've made an ugly but functional bypass for this, bootstrapping the node with a knife command in the recipe and then notifying the machine resource to :converge. Which works.

**Comment by mwrock** [comment]
You might get better traction raising an issue in the [chef-proviioning repo](https://github.com/chef/chef-provisioning) since all the client download/install logic is handled there and not in the driver.
